name: Check Markdown links

# read-write repo token
# access to secrets
# on:
#   workflow_run:
#     workflows: ["Pull Request Preflight Check"]
#     types:
#       - completed
on:
    push:

permissions:
    contents: read

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install markdown-link-check
      run: npm i -g markdown-link-check@3.14.2
    
    - name: Check URLs
      run: |
        find . -name '*.md' -exec markdown-link-check '{}' -q \; || exit 1

